### ISSUE TITLE
Implement Github CI pipeline

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/spark-operator#6]
Can be simple at the beginning: Run maven package/build/test

I just recently did this for one of our other projects and you might be able to use/adapt:

* https://github.com/opencore/gdpdu-java/blob/master/.github/workflows/maven.yml
* Optional: https://github.com/opencore/gdpdu-java/blob/master/.github/workflows/maven-dependency-check.yml
* https://github.com/opencore/gdpdu-java/blob/master/.github/dependabot.yml

This includes also SonarCloud integration which would be great to have but also optional. I can help with setting up the profile etc. (I did this for our other projetcs and I can just copy stuff over).

**Comment by maltesander** [comment]
done
