### ISSUE TITLE
Spark Operator doesn't remove `Installing` state when the installation is done

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/spark-operator#80]
The Spark Operator seems to never remove the Installing condition on the SparkCluster custom resource, even when all pods have been created and are up and running.

**Comment by soenkeliebau** [comment]
ping @maltesander - if you could take a look at this, feel free to reach out if you have questions or cannot reproduce this

**Comment by lfrancke** [comment]
Fixed, condition is set to False
